# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Some step output
      run: echo "hello world!"
    
    - name: Some other step output
      run: echo "hello world again!"

    - name: Test streaming some more complex things
      run: |
        echo "First output"
        sleep 20
        echo "starting loop"
        for i in {1..300}
        do
           echo "Hi $i"
           sleep 0.02
           echo "Done sleeping for $i"
        done
        echo "finished with loop 1"
        sleep 20
        echo "starting loop 2"
        for i in {1..300}
        do
           echo "Hi $i"
           sleep 0.02
           echo "Done sleeping for $i"
        done
        echo "finished with loop 2"
        sleep 20
        echo "We are done!"
