# This is a basic workflow to help you get started with Actions

name: Groups

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        foobar: [a,b,c]
    runs-on: [ubuntu-latest]
    steps:
      - name: Lots of groups
        run: |
          x=1
          while [ $x -le 1000 ]
          do        
            echo "::group::Hello"
            echo "World"
            echo "::endgroup::"
            x=$(( $x + 1 ))
            sleep 1
          done
